mod accessors;
mod benchmark;
mod best_move;
mod deepening;
mod impls;
mod logging;
mod setup;
mod solve;
mod types;
pub type BenchmarkResult = types::BenchmarkResult;
pub type ParallelSolver = types::ParallelSolver;
pub type SearchParams = types::SearchParams;
